[build]
  publish = "dist/review-my-driving/browser"
  functions = "netlify/functions"
  command = "ng build --configuration=production"

[schedule]
  "updateOrderStatus" = "0 * * * *"

[[edge_functions]]
  function = "angular-ssr"
  path = "/*"

[[redirects]]
  from = "/product/:id"
  to = "/product/:id"
  status = 200
  force = true

[[redirects]]
  from = "/orderConfirmation/:id"
  to = "/orderConfirmation/:id"
  status = 200
  force = true